
function iswsl() {
    if [[ $(uname -r) =~ ^.*[Mm]icrosoft.*$ ]]; then
        return 0
    else
        return 1
    fi
}

if ( ! iswsl ); then
    if [[ $(arch) = "arm64" ]]; then; eval "$(/opt/homebrew/bin/brew shellenv)"; fi
    eval "$(pyenv init --path)"
fi
