# Set up local function and Homebrew completion function directories
export FPATH="$HOME/.zfunc:$(brew --prefix)/share/zsh/site-functions:$FPATH"

function iswsl() {
    if [[ $(uname -r) =~ ^.*[Mm]icrosoft.*$ ]]; then
        return 0
    else
        return 1
    fi
}

# Oh My Zsh
export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="robbyrussell"
plugins=(git)
source $ZSH/oh-my-zsh.sh
autoload -U compinit && compinit

# pyenv
eval "$(pyenv init -)"

# used by `git-iamme` and `git-iampg` to set repo-specific email addresses
export PG_EMAIL=mario@pocketgems.com
export PERSONAL_EMAIL=mario@guerrieri.codes

# various variable exports
export WORKSPACE="$HOME/dev"

export EDITOR="code --wait"

export PATH="$HOME/.local/bin:$PATH"
export PATH="$HOME/.npm/bin:$PATH"
if [[ $(arch) = "arm64" ]]; then; export PATH="/opt/homebrew/bin:$PATH"; fi
if [[ $(iswsl) ]]; then; hash -d w=$(wslpath "$(wslvar USERPROFILE)"); fi

export PATH="$PATH:$HOME/Library/Android/sdk/platform-tools"
export GAE_SDK_ROOT="$(brew --caskroom)/google-cloud-sdk/latest/google-cloud-sdk/platform/google_appengine"
export PATH="$PATH:$GAE_SDK_ROOT"
export PYTHONPATH="$GAE_SDK_ROOT:$PYTHONPATH"

# shell completions for Google Cloud
source $(brew --caskroom)/google-cloud-sdk/latest/google-cloud-sdk/completion.zsh.inc
source $(brew --caskroom)/google-cloud-sdk/latest/google-cloud-sdk/path.zsh.inc
