#!/usr/bin/env python
from sh import nativefier
import platform
import os

if platform.processor() == "arm":
    print("Nativefying for ARM")
    arch = "arm64"
else:
    print("Nativefying for x64")
    arch = "x64"

print nativefier("--arch", arch,
                 "--icon", os.path.expandvars("$HOME/icloud/img/icon/ynab.icns"),
                 "app.youneedabudget.com",
                 os.path.expandvars("$HOME/tech/config/scripts/nativefier/apps"))
